# This is a basic workflow to help you get started with Actions

name: syntax-check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo 
        uses: actions/checkout@v1
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y python3
      - run: sudo apt-get install -y python3-pip
      - run: pip install requirements.txt
      - run: pip install pylint
      - name: linting
        run: pylint main.py